import { GRADIENT_MAX_ALT_DEFAULT, GRADIENT_MIN_ALT_DEFAULT } from "./constants.js";

export function createApp() {
  return {
    map: null,
    engine: null,
    computing: false,
    computeShouldStop: false,
    computeStopBarMessage: "",
    computeStopBarClearTimer: null,
    overlayCanvas: null,
    coneState: null,
    openAipConfig: null,
    footerStatusText: "Loading WebGPU…",
    statusClearTimer: null,
    lastGeoLngLat: null,
    lastGeoAltitude: null,
    fakeGeoActive: false,
    geolocateControl: null,
    geoTrackPanZoom: null,
    geoTrackInitialPanPending: false,
    autoComputePending: false,
    autoComputeDebounceTimer: null,
    autoComputeNeedsAirportRefresh: false,
    autoComputeRegion: null,
    singleComputePending: null,
    singleComputeDebounceTimer: null,
    singleLastPick: null,
    computeAirports: [],
    manualAirportSelectMode: false,
    manualStagingAirports: [],
    pendingManualAirport: null,
    pendingManualAirportLayerReady: false,
    cacheSelectMode: false,
    cacheDownloadInProgress: false,
    cacheClearInProgress: false,
    openAipExpiryUpdateInProgress: false,
    pathLayerReady: false,
    contourLayersReady: false,
    sectorBorderLayersReady: false,
    cacheGridReady: false,
    cachedAirportMapReady: false,
    restAirspaceLayersReady: false,
    overlayVisibilityBeforeCache: null,
    overlayVisibilityBeforeManualAirport: null,
    footerCellHtml: null,
    lastInspectAnchor: null,
    lastInspectLngLat: null,
    lastPathScreenBounds: null,
    lastInspectCell: null,
    manualInspectTimeout: null,
    touchHandledRecently: false,
    manualTouchStart: null,
    mapTapStart: null,
    touchGestureWasPan: false,
    appMenuOpen: false,
    glideConesEnabled: false,
    baseMapRaster: "osm",
    gradientMaxAltitude: GRADIENT_MAX_ALT_DEFAULT,
    gradientMinAltitude: GRADIENT_MIN_ALT_DEFAULT,
    gradientSettingsOpen: false,
    openAipVectorEnabled: false,
    iconChActiveModel: null,
    glideSettingsOpen: false,
    iconChSettingsOpen: false,
    selectedCacheCells: new Set(),
    cacheDataWarnings: [],
    interaction: {
      hoverPath: false,
      tapPath: false,
    },
  };
}
