export function createApp() {
  return {
    map: null,
    engine: null,
    computing: false,
    computeShouldStop: false,
    overlayCanvas: null,
    coneState: null,
    openAipConfig: null,
    footerStatusText: "Loading WebGPU…",
    statusClearTimer: null,
    lastGeoLngLat: null,
    lastGeoAltitude: null,
    fakeGeoActive: false,
    geolocateControl: null,
    geoTrackPanZoom: null,
    geoTrackInitialPanPending: false,
    autoComputePending: false,
    autoComputeDebounceTimer: null,
    autoComputeNeedsAirportRefresh: false,
    autoComputeRegion: null,
    singleComputePending: null,
    singleComputeDebounceTimer: null,
    singleLastPick: null,
    pendingSeeds: [],
    manualAirportSelectMode: false,
    manualStagingAirports: [],
    pendingManualAirport: null,
    pendingManualAirportLayerReady: false,
    airportAreaSelectMode: false,
    airportAreaDrawMode: false,
    airportSelectRects: [],
    airportSelectLayersReady: false,
    airportRectInteraction: null,
    cacheSelectMode: false,
    cacheDownloadInProgress: false,
    pathLayerReady: false,
    seedLayersReady: false,
    contourLayersReady: false,
    sectorBorderLayersReady: false,
    cacheGridReady: false,
    cachedAirportMapReady: false,
    restAirspaceLayersReady: false,
    cacheAirportsReady: false,
    overlayVisibilityBeforeCache: null,
    footerCellHtml: null,
    lastInspectAnchor: null,
    lastInspectLngLat: null,
    lastPathScreenBounds: null,
    lastInspectCell: null,
    manualInspectTimeout: null,
    touchHandledRecently: false,
    manualTouchStart: null,
    selectedCacheCells: new Set(),
    interaction: {
      hoverPath: false,
      tapPath: false,
    },
  };
}
